name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # every 24 hours
  workflow_dispatch:      # allow manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    name: generate snake svg
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: madhan404
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: push animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
